In [1]:
# import xml.etree.ElementTree as etree
# import pandas as pd

In [3]:
# tree = etree.parse('fileExample.xml')
# root = tree.getroot()

In [ ]:
# columns = ['Name', 'Phone', 'Birthday']
# df = pd.DataFrame(columns = columns)

In [26]:
import pandas as pd
import seaborn as sns
import requests
import os
import numpy as np
import json

In [10]:
print(pd.__version__)

1.5.3

In [8]:
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/data/addresses.csv"

df = pd.read_csv(url, header=None)

print(df.head())

               0         1                                 2          3    4  \
0           John       Doe                 120 jefferson st.  Riverside   NJ
1           Jack  McGinnis                      220 hobo Av.      Phila   PA
2  John "Da Man"    Repici                 120 Jefferson St.  Riverside   NJ
3        Stephen     Tyler  7452 Terrace "At the Plaza" road   SomeTown   SD
4            NaN  Blankman                               NaN   SomeTown   SD

       5
0   8075
1   9119
2   8075
3  91234
4    298

In [11]:
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/data/addresses.csv"

response = requests.get(url)

with open("addresses.csv", "wb") as f:
    f.write(response.content)

In [13]:
df = pd.read_csv("addresses.csv", header=None)
df

,0,1,2,3,4,5
0,John,Doe,120 jefferson st.,Riverside,NJ,8075
1,Jack,McGinnis,220 hobo Av.,Phila,PA,9119
2,"John ""Da Man""",Repici,120 Jefferson St.,Riverside,NJ,8075
3,Stephen,Tyler,"7452 Terrace ""At the Plaza"" road",SomeTown,SD,91234
4,NaN,Blankman,NaN,SomeTown,SD,298
5,"Joan ""the bone"", Anne",Jet,"9th, at Terrace plc",Desert City,CO,123

In [15]:
print(os.getcwd())

C:\Users\HOME\PycharmProjects\2026_upgrade_ds_math_genAI\py_REST_APIs

In [16]:
df.columns =['First Name', 'Last Name', 'Location ', 'City','State','Area Code']

In [17]:
df

,First Name,Last Name,Location,City,State,Area Code
0,John,Doe,120 jefferson st.,Riverside,NJ,8075
1,Jack,McGinnis,220 hobo Av.,Phila,PA,9119
2,"John ""Da Man""",Repici,120 Jefferson St.,Riverside,NJ,8075
3,Stephen,Tyler,"7452 Terrace ""At the Plaza"" road",SomeTown,SD,91234
4,NaN,Blankman,NaN,SomeTown,SD,298
5,"Joan ""the bone"", Anne",Jet,"9th, at Terrace plc",Desert City,CO,123

In [18]:
df["First Name"]

0                     John
1                     Jack
2            John "Da Man"
3                  Stephen
4                      NaN
5    Joan "the bone", Anne
Name: First Name, dtype: object

In [19]:
df = df[['First Name', 'Last Name', 'Location ', 'City','State','Area Code']]
df

,First Name,Last Name,Location,City,State,Area Code
0,John,Doe,120 jefferson st.,Riverside,NJ,8075
1,Jack,McGinnis,220 hobo Av.,Phila,PA,9119
2,"John ""Da Man""",Repici,120 Jefferson St.,Riverside,NJ,8075
3,Stephen,Tyler,"7452 Terrace ""At the Plaza"" road",SomeTown,SD,91234
4,NaN,Blankman,NaN,SomeTown,SD,298
5,"Joan ""the bone"", Anne",Jet,"9th, at Terrace plc",Desert City,CO,123

In [20]:
# To select the first row
df.loc[0]

First Name                 John
Last Name                   Doe
Location      120 jefferson st.
City                  Riverside
State                        NJ
Area Code                  8075
Name: 0, dtype: object

In [21]:
# To select the 0th,1st and 2nd row of "First Name" column only
df.loc[[0,1,2], "First Name" ]

0             John
1             Jack
2    John "Da Man"
Name: First Name, dtype: object

In [23]:
#creating a dataframe
df=pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), columns=['a', 'b', 'c'])
df

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [24]:
#applying the transform function
df = df.transform(func = lambda x : x + 10)
df

    a   b   c
0  11  12  13
1  14  15  16
2  17  18  19

In [25]:
result = df.transform(func = ['sqrt'])
result

          a         b         c
       sqrt      sqrt      sqrt
0  3.316625  3.464102  3.605551
1  3.741657  3.872983  4.000000
2  4.123106  4.242641  4.358899

In [27]:
person = {
    'first_name' : 'Mark',
    'last_name' : 'abc',
    'age' : 27,
    'address': {
        "streetAddress": "21 2nd Street",
        "city": "New York",
        "state": "NY",
        "postalCode": "10021-3100"
    }
}
person

{'first_name': 'Mark',
 'last_name': 'abc',
 'age': 27,
 'address': {'streetAddress': '21 2nd Street',
  'city': 'New York',
  'state': 'NY',
  'postalCode': '10021-3100'}}

### json.dumps() that helps in converting a dictionary to a JSON object.

It takes two parameters:
* ```dictionary``` – name of the dictionary which should be converted to JSON object.
* ```indent``` – defines the number of units for indentation

In [28]:
with open('person.json', 'w') as f:  # writing JSON object
    json.dump(person, f)

In [31]:
# Serializing json
json_object = json.dumps(person, indent = 4)

# Writing to sample.json
with open("sample.json", "w") as outfile:
    outfile.write(json_object)

In [32]:
print(json_object)

{
    "first_name": "Mark",
    "last_name": "abc",
    "age": 27,
    "address": {
        "streetAddress": "21 2nd Street",
        "city": "New York",
        "state": "NY",
        "postalCode": "10021-3100"
    }
}

In [33]:
# Opening JSON file
with open('sample.json', 'r') as openfile:

    # Reading from json file
    json_object = json.load(openfile)

print(json_object)
print(type(json_object))

{'first_name': 'Mark', 'last_name': 'abc', 'age': 27, 'address': {'streetAddress': '21 2nd Street', 'city': 'New York', 'state': 'NY', 'postalCode': '10021-3100'}}
<class 'dict'>

In [34]:
import xml.etree.ElementTree as ET

In [35]:
# create the file structure
employee = ET.Element('employee')
details = ET.SubElement(employee, 'details')
first = ET.SubElement(details, 'firstname')
second = ET.SubElement(details, 'lastname')
third = ET.SubElement(details, 'age')
first.text = 'Shiv'
second.text = 'Mishra'
third.text = '23'

# create a new XML file with the results
mydata1 = ET.ElementTree(employee)
# myfile = open("items2.xml", "wb")
# myfile.write(mydata)
with open("new_sample.xml", "wb") as files:
    mydata1.write(files)

In [40]:
import xml.etree.ElementTree as etree
import requests

In [41]:
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/data/Sample-employee-XML-file.xml"

response = requests.get(url)

root = etree.fromstring(response.content)

print(root.tag)

employees

In [42]:
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/data/Sample-employee-XML-file.xml"

response = requests.get(url)

with open("Sample-employee-XML-file.xml", "wb") as f:
    f.write(response.content)

In [43]:
tree = etree.parse("Sample-employee-XML-file.xml")
root = tree.getroot()

print(root.tag)

employees

In [45]:
root = etree.fromstring(response.content)
root

In [46]:
for child in root:
    print(child.tag, child.text)

details

details

details

details

In [48]:
# Parse the XML file
tree = etree.parse("Sample-employee-XML-file.xml")

# Get the root of the XML tree
root = tree.getroot()

# Define the columns for the DataFrame
columns = ["firstname", "lastname", "title", "division", "building", "room"]

# Initialize an empty DataFrame
datatframe = pd.DataFrame(columns=columns)

# Iterate through each node in the XML root
for node in root:
    # Extract text from each element
    firstname = node.find("firstname").text
    lastname = node.find("lastname").text
    title = node.find("title").text
    division = node.find("division").text
    building = node.find("building").text
    room = node.find("room").text

    # Create a DataFrame for the current row
    row_df = pd.DataFrame([[firstname, lastname, title, division, building, room]], columns=columns)

    # Concatenate with the existing DataFrame
    datatframe = pd.concat([datatframe, row_df], ignore_index=True)

In [49]:
# Herein xpath we mention the set of xml nodes to be considered for migrating  to the dataframe which in this case is details node under employees.
df=pd.read_xml("Sample-employee-XML-file.xml", xpath="/employees/details")
df

  firstname lastname      title  division  building  room
0      Shiv   Mishra   Engineer  Computer       301    11
1       Yuh    Datta  developer  Computer       303     2
2     Rahil     Khan     Tester  Computer       304    10
3      Deep   Parekh   Designer  Computer       305    14

In [50]:
datatframe.to_csv("employee.csv", index=False)

In [52]:
# importing PIL
from PIL import Image