In [1]:
import numpy as np
import pandas as pd

In [23]:
def warn(*args, **kwargs):
    pass

import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

In [24]:
URL="https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29"

In [25]:
# Extract tables from webpage using Pandas.
tables = pd.read_html(URL)
tables

[      0     1     2
 0   Aug   SEP   Oct
 1   NaN    02   NaN
 2  2022  2023  2024,
                                                    0
 0  Largest economies in the world by GDP (nominal...,
                                                    0  \
 0  .mw-parser-output .legend{page-break-inside:av...

                                                    1  \
 0  $750 billion – $1 trillion $500–750 billion $2...

                                                    2
 0  $50–100 billion $25–50 billion $5–25 billion <...  ,
     Country/Territory UN region IMF[1][13]            World Bank[14]  \
     Country/Territory UN region   Estimate       Year       Estimate
 0               World         —  105568776       2023      100562011
 1       United States  Americas   26854599       2023       25462700
 2               China      Asia   19373586  [n 1]2023       17963171
 3               Japan      Asia    4409738       2023        4231141
 4             Germany    Europe    4308854       2023        4072192
 ..                ...       ...        ...        ...            ...
 209          Anguilla  Americas          —          —              —
 210          Kiribati   Oceania        248       2023            223
 211             Nauru   Oceania        151       2023            151
 212        Montserrat  Americas          —          —              —
 213            Tuvalu   Oceania         65       2023             60

                United Nations[15]
           Year           Estimate       Year
 0         2022           96698005       2021
 1         2022           23315081       2021
 2    [n 3]2022           17734131  [n 1]2021
 3         2022            4940878       2021
 4         2022            4259935       2021
 ..         ...                ...        ...
 209          —                303       2021
 210       2022                227       2021
 211       2022                155       2021
 212          —                 72       2021
 213       2022                 60       2021

 [214 rows x 8 columns],
   .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar a>span,.mw-parser-output .navbar a>abbr{text-decoration:inherit}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}vteLists of countries by financial rankings  \
 0                                              Trade
 1                                         Investment
 2                                              Funds
 3                                    Budget and debt
 4                                   Income and taxes
 5                                         Bank rates
 6                                           Currency
 7                                              Other
 8  Lists of countries by GDP rankings List of int...

   .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar a>span,.mw-parser-output .navbar a>abbr{text-decoration:inherit}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}vteLists of countries by financial rankings.1
 0  Account balance % of GDP Exports by product me...
 1                   FDI received past FDI abroad GFI
 2  Forex reserves Forex reserves (ex. gold) Gold ...
 3  Government budget PPP % of GDP per capita Cred...
 4  Tax rates Inheritance tax Tax revenue Wage ave...
 5  Central bank interest rate Commercial bank pri...
 6               Exchange rates to US$ Inflation rate
 7  Financial Development Index Average annual lab...
 8  Lists of countries by GDP rankings List of int...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ,
                vteLists of countries by GDP rankings  \
 0                                            Nominal
 1                      Purchasing power parity (PPP)
 2                                        Growth rate
 3                        Gross national income (GNI)
 4                                Countries by region
 5                              Subnational divisions
 6  Lists of countries by financial rankings List ...

              vteLists of countries by GDP rankings.1
 0  Per capita Past and projected per capita Secto...
 1  Per capita Past per capita Past and projected ...
 2  African countries Asian states European Union ...
 3                  PPP per capita Nominal per capita
 4  Africa PPP nominal Commonwealth of Nations PPP...
 5  Albania Argentina Australia Austria Baltic Sta...
 6  Lists of countries by financial rankings List ...  ,
               vteEconomic classification of countries  \
 0   Developed country Developing country Least dev...
 1                                   Three-World Model
 2                        Gross domestic product (GDP)
 3                                             Nominal
 4                       Purchasing power parity (PPP)
 5                         Gross national income (GNI)
 6                                               Wages
 7                                              Wealth
 8                             Other national accounts
 9                                   Human development
 10                                     Digital divide
 11       Net international investment position (NIIP)
 12                    Economics portal • World portal

             vteEconomic classification of countries.1
 0   Developed country Developing country Least dev...
 1   First World Second World Third World Fourth World
 2   Nominal By country past and projected per capi...
 3   By country past and projected per capita per c...
 4   By country future estimates per capita per cap...
 5   (Nominal, Atlas method) per capita (PPP) per c...
 6   Average wage Europe Employee compensation (per...
 7   Wealth per adult Europe Financial assets per c...
 8   Gross National Happiness Net material product ...
 9   Human Development Index by country inequality-...
 10  ICT Development Index Number of broadband Inte...
 11        Per capita (creditors) Per capita (debtors)
 12                    Economics portal • World portal  ,
                                0  \
 0                        Nominal
 1  Purchasing power parity (PPP)

                                                    1
 0  By country past and projected per capita per c...
 1  By country future estimates per capita per cap...  ]

In [26]:
# Retain table number 3 as the required dataframe.
df = tables[3]
df.head(4)

  Country/Territory UN region IMF[1][13]            World Bank[14]             \
  Country/Territory UN region   Estimate       Year       Estimate       Year
0             World         —  105568776       2023      100562011       2022
1     United States  Americas   26854599       2023       25462700       2022
2             China      Asia   19373586  [n 1]2023       17963171  [n 3]2022
3             Japan      Asia    4409738       2023        4231141       2022

  United Nations[15]
            Estimate       Year
0           96698005       2021
1           23315081       2021
2           17734131  [n 1]2021
3            4940878       2021

In [27]:
# Replace the column headers with column numbers
df.columns = range(df.shape[1])
df.head(5)

,0,1,2,3,4,5,6,7
0,World,—,105568776,2023,100562011,2022,96698005,2021
1,United States,Americas,26854599,2023,25462700,2022,23315081,2021
2,China,Asia,19373586,[n 1]2023,17963171,[n 3]2022,17734131,[n 1]2021
3,Japan,Asia,4409738,2023,4231141,2022,4940878,2021
4,Germany,Europe,4308854,2023,4072192,2022,4259935,2021

In [28]:
# Retain columns with index 0 and 2 (name of country and value of GDP quoted by IMF)
df = df[[0, 2]]
df.head(3)

               0          2
0          World  105568776
1  United States   26854599
2          China   19373586

In [29]:
# Retain the Rows with index 1 to 10, indicating the top 10 economies of the world.
df = df.iloc[1:11]
df

                 0         2
1    United States  26854599
2            China  19373586
3            Japan   4409738
4          Germany   4308854
5            India   3736882
6   United Kingdom   3158938
7           France   2923489
8            Italy   2169745
9           Canada   2089672
10          Brazil   2081235

In [30]:
# Assign column names as "Country" and "GDP (Million USD)"
# Переименовываем столбцы
df.columns = ["Country", "GDP (Million USD)"]

df

           Country GDP (Million USD)
1    United States          26854599
2            China          19373586
3            Japan           4409738
4          Germany           4308854
5            India           3736882
6   United Kingdom           3158938
7           France           2923489
8            Italy           2169745
9           Canada           2089672
10          Brazil           2081235

In [32]:
# Change the data type of the 'GDP (Million USD)' column to integer. Use astype() method.

df["GDP (Million USD)"] = df["GDP (Million USD)"].astype(int)

In [33]:
# Convert the GDP value in Million USD to Billion USD

df["GDP (Million USD)"] = df["GDP (Million USD)"] / 1_000_000

In [34]:
df

           Country  GDP (Million USD)
1    United States          26.854599
2            China          19.373586
3            Japan           4.409738
4          Germany           4.308854
5            India           3.736882
6   United Kingdom           3.158938
7           France           2.923489
8            Italy           2.169745
9           Canada           2.089672
10          Brazil           2.081235

In [35]:
# Use numpy.round() method to round the value to 2 decimal places.
df["GDP (Million USD)"] = df["GDP (Million USD)"].round(2)

In [36]:
df["GDP (Million USD)"] = np.round(df["GDP (Million USD)"], 2)

In [37]:
# Rename the column header from 'GDP (Million USD)' to 'GDP (Billion USD)'
# Переименовываем столбец
df = df.rename(columns={"GDP (Million USD)": "GDP (Billion USD)"})

df

           Country  GDP (Billion USD)
1    United States              26.85
2            China              19.37
3            Japan               4.41
4          Germany               4.31
5            India               3.74
6   United Kingdom               3.16
7           France               2.92
8            Italy               2.17
9           Canada               2.09
10          Brazil               2.08

In [38]:
# Load the DataFrame to the CSV file named "Largest_economies.csv"
df.to_csv('./Largest_economies.csv')